name: Build and Push .NET Package

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main

    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

    - name: Build
      run: dotnet build MortgageCalculator/MortgageCalcClass/MortgageCalcCLass.csproj --configuration Release /p:Version=${VERSION}

    - name: Test
      run: dotnet test MortgageCalculator/MortgageCalcClass/MortgageCalcCLass.csproj --configuration Release /p:Version=${VERSION} --no-build

    - name: Pack
      run: dotnet pack MortgageCalculator/MortgageCalcClass/MortgageCalcCLass.csproj --configuration Release /p:Version=${VERSION} --no-build --output . -p:PackageID=RhettMortgageCalcClassLibrary

    - name: Push
      run: dotnet nuget push RhettMortgageCalcClassLibrary.${VERSION}.nupkg --source https://nuget.pkg.github.com/rhettchase/index.json --api-key ${{ secrets.NUGET_PAT }}
      env:
        GITHUB_TOKEN: ${{ secrets.NUGET_PAT }}
